export interface VocabularyTerm {
  term: string;
  definition: string;
  category: string;
}

export const vocabularyTerms: VocabularyTerm[] = [
  {
    term: '2FA (Two-Factor Authentication)',
    definition: 'Security method that requires two verification factors to access an account (typically a password + a code generated by an app or sent via SMS).',
    category: 'Security'
  },
  {
    term: 'OGE (Original Gmail Email)',
    definition: 'The original Gmail address used when creating the account. Crucial for account recovery and security.',
    category: 'Security'
  },
  {
    term: 'MFA (Multi-Factor Authentication)',
    definition: 'Multi-factor authentication, similar to 2FA but can use more than two verification methods (password, SMS, email, biometrics, etc.).',
    category: 'Security'
  },
  {
    term: 'Authenticator App',
    definition: 'Mobile application that generates temporary verification codes for two-factor authentication (e.g., Google Authenticator, Microsoft Authenticator).',
    category: 'Security'
  },
  {
    term: 'Secret Key / Secret Code',
    definition: 'Unique alphanumeric code (usually 16 or 32 characters) used to set up an authenticator. Keep it safe as it allows recreating 2FA codes.',
    category: 'Security'
  },
  {
    term: 'Recovery Code',
    definition: 'Unique backup codes that allow access to an account if the authenticator is lost or inaccessible. Must be saved.',
    category: 'Security'
  },
  {
    term: 'Session',
    definition: 'Active connection to an account from a device or browser. It is recommended to monitor and delete unauthorized sessions.',
    category: 'Security'
  },
  {
    term: 'Pullback',
    definition: 'Action where the previous account owner attempts to regain control by using recovery information (email, phone) still linked to the account.',
    category: 'Security'
  },
  {
    term: 'Alias Email',
    definition: 'Secondary email address associated with a primary account. Allows receiving emails at multiple addresses while managing a single account.',
    category: 'Account Management'
  },
  {
    term: 'Device Management',
    definition: 'Management of devices connected to an account. Allows viewing and removing devices authorized to access the account.',
    category: 'Account Management'
  },
  {
    term: 'Authorized Apps',
    definition: 'Third-party applications that have been granted permission to access certain account data. It is recommended to revoke them regularly.',
    category: 'Account Management'
  },
  {
    term: 'Steam Guard',
    definition: 'Steam security system using a mobile authenticator or email codes to protect transactions and logins.',
    category: 'Platforms'
  },
  {
    term: 'SDA (Steam Desktop Authenticator)',
    definition: 'Alternative desktop application to manage Steam Guard, allowing authentication code generation on a computer.',
    category: 'Platforms'
  },
  {
    term: 'SteamID64',
    definition: 'Unique 17-digit numeric identifier associated with a Steam account. Used to uniquely identify a Steam profile.',
    category: 'Platforms'
  },
  {
    term: 'Password Reset Protection',
    definition: 'Feature that prevents password reset without additional verification, strengthening account security.',
    category: 'Security'
  },
  {
    term: 'Email Forwarding',
    definition: 'Feature that automatically redirects received emails to another address. Should be disabled when securing an account to avoid interception.',
    category: 'Security'
  },
  {
    term: 'Passkey',
    definition: 'Modern authentication method using public key cryptography. More secure than traditional passwords.',
    category: 'Security'
  },
  {
    term: 'Retail Key / Product Key',
    definition: 'Physical or digital product key purchased in-store (as opposed to a key purchased directly online). Often required for account recovery.',
    category: 'Platforms'
  },
  {
    term: 'DOB (Date of Birth)',
    definition: 'Date of birth associated with an account. Often used for identity verification. Warning: modifying it can lock the account.',
    category: 'Account Management'
  },
  {
    term: 'Linked Accounts',
    definition: 'External accounts (Google, Apple, Facebook, etc.) connected to a primary account. Can be used for login or recovery.',
    category: 'Account Management'
  },
  {
    term: 'Account Creation Email',
    definition: 'Initial email received when creating the account. Often contains important information about the date and origin of the account.',
    category: 'Account Management'
  }
];
